name: NMS_CADVISOR_NAME
services:
  cadvisor:
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    image: gcr.io/cadvisor/cadvisor:${CADVISOR_VERSION}
    user: root
    container_name: NMS_CADVISOR_NAME
    restart: always
    network_mode: host
    env_file:
      - .env
    command:
        - -port=NMS_CADVISOR_PORT
        
